Added GHA test steps
orisintel/laravel-online-migrator pull request #27
Opened 2020-10-27 00:35 UTC by qschmick

Setting up running tests on GHA

2020-10-27 00:39 UTC, tomschlick requested changes

2020-10-27 00:39 UTC, tomschlick commented on .php_cs.cache
> +{"php":"7.4.10","version":"2.16.4","indent":"    ","lineEnding":"\n","rules":{"array_syntax":{"syntax":"short"},"align_multiline_comment":{"comment_type":"phpdocs_only"},"binary_operator_spaces":{"al
This file should be added to the `.gitignore`

2020-10-27 02:32 UTC, tomschlick approved these changes

2021-03-10 17:26 UTC, qschmick commented
@tomschlick Just FYI, I don't have write access so I can't merge in this PR.

2021-03-10 18:32 UTC, merged